import type { LocaleData } from "../../types";

export const address: Partial<LocaleData> = {
  addressFormats: {'{{street_address}}, {{city}}, {{city_state}}': 100.0},
  buildingNumberFormats: ['%', '%', '%', '%#', '%#', '%#', '%#', '%##', '%-%', '?-##-##', '%?-##'],
  building_prefixes: ['', '', '', '', '', '', 'No. ', 'No. ', 'No. ', 'Lot '],
  cityFormats: ['{{city_prefix}} {{city_suffix}}', '{{city_prefix}} {{city_suffix}}', '{{city_prefix}} {{city_suffix}}', '{{city_prefix}} {{city_suffix}}', '{{city_prefix}} {{city_suffix}}', '{{city_prefix}} {{city_suffix}}', '{{city_prefix_abbr}}%', '{{city_prefix_abbr}}%#', '{{city_prefix_abbr}}%#?'],
  cityPrefixes: ['Alam', 'Apartment', 'Ara', 'Bandar', 'Bandar', 'Bandar', 'Bandar', 'Bandar', 'Bandar', 'Bandar Bukit', 'Bandar Seri', 'Bandar Sri', 'Bandar Baru', 'Batu', 'Bukit', 'Desa', 'Damansara', 'Kampung', 'Kampung Baru', 'Kampung Baru', 'Kondominium', 'Kota', 'Laman', 'Lembah', 'Medan', 'Pandan', 'Pangsapuri', 'Petaling', 'Puncak', 'Seri', 'Sri', 'Taman', 'Taman', 'Taman', 'Taman', 'Taman', 'Taman', 'Taman Desa'],
  citySuffixes: ['Aman', 'Amanjaya', 'Anggerik', 'Angkasa', 'Antarabangsa', 'Awan', 'Bahagia', 'Bangsar', 'Baru', 'Belakong', 'Bendahara', 'Bestari', 'Bintang', 'Brickfields', 'Casa', 'Changkat', 'Country Heights', 'Damansara', 'Damai', 'Dato Harun', 'Delima', 'Duta', 'Flora', 'Gembira', 'Genting', 'Harmoni', 'Hartamas', 'Impian', 'Indah', 'Intan', 'Jasa', 'Jaya', 'Keramat', 'Kerinchi', 'Kiara', 'Kinrara', 'Kuchai', 'Laksamana', 'Mahkota', 'Maluri', 'Manggis', 'Maxwell', 'Medan', 'Melawati', 'Menjalara', 'Meru', 'Mulia', 'Mutiara', 'Pahlawan', 'Perdana', 'Pertama', 'Permai', 'Pelangi', 'Petaling', 'Pinang', 'Puchong', 'Puteri', 'Putra', 'Rahman', 'Rahmat', 'Raya', 'Razak', 'Ria', 'Saujana', 'Segambut', 'Selamat', 'Selatan', 'Semarak', 'Sentosa', 'Seputeh', 'Setapak', 'Setia Jaya', 'Sinar', 'Sungai Besi', 'Sungai Buaya', 'Sungai Long', 'Suria', 'Tasik Puteri', 'Tengah', 'Timur', 'Tinggi', 'Tropika', 'Tun Hussein Onn', 'Tun Perak', 'Tunku', 'Ulu', 'Utama', 'Utara', 'Wangi'],
  city_prefix_abbrs: ['SS', 'Seksyen ', 'PJS', 'PJU', 'USJ '],
  states: {'JHR': ['Johor Darul Ta\'zim', 'Johor'], 'KDH': ['Kedah Darul Aman', 'Kedah'], 'KTN': ['Kelantan Darul Naim', 'Kelantan'], 'KUL': ['KL', 'Kuala Lumpur', 'WP Kuala Lumpur'], 'LBN': ['Labuan'], 'MLK': ['Malacca', 'Melaka'], 'NSN': ['Negeri Sembilan Darul Khusus', 'Negeri Sembilan'], 'PHG': ['Pahang Darul Makmur', 'Pahang'], 'PNG': ['Penang', 'Pulau Pinang'], 'PRK': ['Perak Darul Ridzuan', 'Perak'], 'PLS': ['Perlis Indera Kayangan', 'Perlis'], 'PJY': ['Putrajaya'], 'SBH': ['Sabah'], 'SWK': ['Sarawak'], 'SGR': ['Selangor Darul Ehsan', 'Selangor'], 'TRG': ['Terengganu Darul Iman', 'Terengganu']},
  states_postcode: {'PLS': [[1000, 2800]], 'KDH': [[5000, 9810]], 'PNG': [[10000, 14400]], 'KTN': [[15000, 18500]], 'TRG': [[20000, 24300]], 'PHG': [[25000, 28800], [39000, 39200], [49000, 69000]], 'PRK': [[30000, 36810]], 'SGR': [[40000, 48300], [63000, 68100]], 'KUL': [[50000, 60000]], 'PJY': [[62000, 62988]], 'NSN': [[70000, 73509]], 'MLK': [[75000, 78309]], 'JHR': [[79000, 86900]], 'LBN': [[87000, 87033]], 'SBH': [[88000, 91309]], 'SWK': [[93000, 98859]]},
  streetAddressFormats: ['{{building_prefix}}{{building_number}}, {{street_name}}'],
  streetNameFormats: ['{{street_prefix}} %', '{{street_prefix}} %/%', '{{street_prefix}} %/%#', '{{street_prefix}} %/%?', '{{street_prefix}} %/%#?', '{{street_prefix}} %?', '{{street_prefix}} %#?', '{{street_prefix}} {{street_suffix}}', '{{street_prefix}} {{street_suffix}} %', '{{street_prefix}} {{street_suffix}} %/%', '{{street_prefix}} {{street_suffix}} %/%#', '{{street_prefix}} {{street_suffix}} %/%?', '{{street_prefix}} {{street_suffix}} %/%#?', '{{street_prefix}} {{street_suffix}} %?', '{{street_prefix}} {{street_suffix}} %#?'],
  streetPrefixes: ['Jln', 'Jln', 'Jalan', 'Jalan', 'Jalan', 'Lorong'],
  streetSuffixes: ['Air Itam', 'Alor', 'Ampang', 'Ampang Hilir', 'Anson', 'Ariffin', 'Bangsar', 'Baru', 'Bellamy', 'Birch', 'Bijih Timah', 'Bukit Aman', 'Bukit Bintang', 'Bukit Petaling', 'Bukit Tunku', 'Cantonment', 'Cenderawasih', 'Chan Sow Lin', 'Chow Kit', 'Cinta', 'Cochrane', 'Conlay', 'D. S. Ramanathan', 'Damansara', 'Dang Wangi', 'Davis', 'Dewan Bahasa', 'Dato Abdul Rahman', 'Dato\'Keramat', 'Dato\' Maharaja Lela', 'Doraisamy', 'Eaton', 'Faraday', 'Galloway', 'Genting Klang', 'Gereja', 'Hang Jebat', 'Hang Kasturi', 'Hang Lekir', 'Hang Lekiu', 'Hang Tuah', 'Hospital', 'Imbi', 'Istana', 'Jelutong', 'Kampung Attap', 'Kebun Bunga', 'Kedah', 'Keliling', 'Kia Peng', 'Kinabalu', 'Kuala Kangsar', 'Kuching', 'Ledang', 'Lembah Permai', 'Loke Yew', 'Lt. Adnan', 'Lumba Kuda', 'Madras', 'Magazine', 'Maharajalela', 'Masjid', 'Maxwell', 'Mohana Chandran', 'Muda', 'P. Ramlee', 'Padang Kota Lama', 'Pahang', 'Pantai Baharu', 'Parlimen', 'Pasar', 'Pasar Besar', 'Perak', 'Perdana', 'Petaling', 'Prangin', 'Pudu', 'Pudu Lama', 'Raja', 'Raja Abdullah', 'Raja Chulan', 'Raja Laut', 'Rakyat', 'Residensi', 'Robson', 'S.P. Seenivasagam', 'Samarahan 1', 'Selamat', 'Sempadan', 'Sentul', 'Serian 1', 'Sasaran', 'Sin Chee', 'Sultan Abdul Samad', 'Sultan Azlan Shah', 'Sultan Iskandar', 'Sultan Ismail', 'Sultan Sulaiman', 'Sungai Besi', 'Syed Putra', 'Tan Cheng Lock', 'Thambipillay', 'Tugu', 'Tuanku Abdul Halim', 'Tuanku Abdul Rahman', 'Tun Abdul Razak', 'Tun Dr Ismail', 'Tun H S Lee', 'Tun Ismail', 'Tun Perak', 'Tun Razak', 'Tun Sambanthan', 'U-Thant', 'Utama', 'Vermont', 'Vivekananda', 'Wan Kadir', 'Wesley', 'Wisma Putra', 'Yaacob Latif', 'Yap Ah Loy', 'Yap Ah Shak', 'Yap Kwan Seng', 'Yew', 'Zaaba', 'Zainal Abidin'],
};
