import type { LocaleData } from "../../types";

export const address: Partial<LocaleData> = {
  addressFormats: ['{{street_address}}\n{{city}} {{postcode}}'],
  buildingNumberFormats: ['%##', '%#', '%'],
  cityFormats: ['{{first_name}}{{city_suffix}}', '{{last_name}}{{city_suffix}}', '{{last_name}}{{city_suffix}}', '{{last_name}}{{city_suffix}}', '{{last_name}}{{city_suffix}}', '{{last_name}}{{city_suffix}}', '{{city_prefix}} {{last_name}}{{city_suffix}}', '{{te_reo_first}}{{te_reo_ending}}', '{{te_reo_first}}{{te_reo_ending}}', '{{te_reo_first}}{{te_reo_ending}}', '{{te_reo_first}}{{te_reo_ending}}', '{{te_reo_first}}{{te_reo_part}}{{te_reo_ending}}', '{{te_reo_first}}{{te_reo_part}}{{te_reo_ending}}'],
  cityPrefixes: ['North', 'East', 'West', 'South', 'New', 'Lake', 'Port', 'Upper', 'Lower', 'High', 'Mount'],
  citySuffixes: ['town', 'ton', 'land', 'ville', 'berg', 'burgh', 'borough', 'bury', 'burn', 'ing', 'port', 'mouth', 'stone', 'ings', 'mouth', 'fort', 'haven', 'leigh', 'side', 'gate', 'neath', 'side', ' Flats', ' Hill'],
  postcodeFormats: ['0%##', '1###', '20##', '21##', '22##', '23##', '24##', '25##', '26##', '3###', '4###', '50##', '51##', '52##', '53##', '55##', '57##', '58##', '60##', '61##', '62##', '64##', '69##', '7###', '80##', '81##', '82##', '84##', '85##', '86##', '88##', '89##', '90##', '92##', '93##', '94##', '95##', '96##', '97##', '98##'],
  secondaryAddressFormats: ['Apt. %##', 'Flat %#', 'Suite %##', 'Unit %#', 'Level %'],
  streetAddressFormats: ['{{building_number}} {{street_name}}', '{{building_number}} {{street_name}}', '{{building_number}} {{street_name}}', '{{building_number}} {{street_name}}\nRD {{rd_number}}', '{{secondary_address}}\n{{building_number}} {{street_name}}', 'PO Box {{building_number}}'],
  streetNameFormats: ['{{first_name}} {{street_suffix}}', '{{last_name}} {{street_suffix}}', '{{last_name}} {{street_suffix}}', '{{last_name}} {{street_suffix}}', '{{last_name}}-{{last_name}} {{street_suffix}}', '{{te_reo_first}}{{te_reo_ending}} {{street_suffix}}', '{{te_reo_first}}{{te_reo_ending}} {{street_suffix}}', '{{te_reo_first}}{{te_reo_part}}{{te_reo_ending}} {{street_suffix}}'],
  streetSuffixes: ['Arcade', 'Arcade', 'Arcade', 'Avenue', 'Avenue', 'Avenue', 'Avenue', 'Avenue', 'Avenue', 'Avenue', 'Avenue', 'Beach Road', 'Beach Road', 'Beach Road', 'Beach Road', 'Crescent', 'Crescent', 'Crescent', 'Crescent', 'Crescent', 'Drive', 'Drive', 'Drive', 'Drive', 'Mews', 'Mews', 'Mews', 'Place', 'Place', 'Place', 'Place', 'Range Road', 'Range Road', 'Road', 'Road', 'Road', 'Road', 'Road', 'Road', 'Road', 'Road', 'Road', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Street', 'Terrace', 'Terrace', 'Terrace', 'Way', 'Way', 'Way', 'Access', 'Alley', 'Alleyway', 'Amble', 'Anchorage', 'Approach', 'Broadway', 'Bypass', 'Causeway', 'Centre', 'Circle', 'Circuit', 'Close', 'Concourse', 'Copse', 'Corner', 'Court', 'Cove', 'Crest', 'Cross', 'Crossing', 'Cutting', 'Esplanade', 'Flats', 'Gardens', 'Grove', 'Heights', 'Highway', 'Lane', 'Line', 'Keys', 'Parade', 'Park', 'Pass', 'Plaza', 'Point', 'Quay', 'Reserve', 'Ridge', 'Rise', 'Square', 'Track', 'Trail', 'View'],
  te_reo_endings: ['hanga', 'hope', 'iti', 'iti', 'kiwi', 'makau', 'nui', 'nui', 'nui', 'nuku', 'roa', 'rua', 'tanga', 'tapu', 'toa', 'whenua', 'whero', 'whitu'],
  te_reo_parts: ['ara', 'awa', 'horo', 'kawa', 'koro', 'kowhai', 'manawa', 'mata', 'maunga', 'moko', 'motu', 'ngauru', 'papapa', 'po', 'puke', 'rangi', 'rohe', 'rongo', 'roto', 'tahi', 'tai', 'tangi', 'tau', 'tere', 'tipu', 'wai', 'waka', 'whaka', 'whanga', 'whare', 'weka'],
};
