import type { LocaleData } from "../../types";

export const misc: Partial<LocaleData> = {
  gemstone_names: ['Agate', 'Amber', 'Amethyst', 'Aquamarine', 'Citrine', 'Diamond', 'Emerald', 'Garnet', 'Jade', 'Jasper', 'Lapis Lazuli', 'Moonstone', 'Onyx', 'Opal', 'Peridot', 'Ruby', 'Sapphire', 'Sardonyx', 'Sunstone', 'Topaz', 'Turquoise', 'Zircon'],
  mountain_names: ['Apo', 'Arayat', 'Atok', 'Banahaw', 'Bulusan', 'Caraballo', 'Cordillera', 'Cresta', 'Halcon', 'Hibok-Hibok', 'Iriga', 'Kanlaon', 'Makiling', 'Malinao', 'Mariveles', 'Matumtum', 'Mayon', 'Palali', 'Palanan', 'Pao', 'Pinatubo', 'Samat', 'Sicaba', 'Sierra Madre', 'Tabayoc'],
  plant_names: ['Acacia', 'Agoho', 'Akle', 'Anahaw', 'Anonas', 'Anubing', 'Aranga', 'Asparagus', 'Atis', 'Avocado', 'Azalea', 'Azucena', 'Bagtikan', 'Bakawan', 'Balete', 'Balimbing', 'Banaba', 'Banuyo', 'Banyan', 'Baticulin', 'Batino', 'Bauhinia', 'Bouganvilla', 'Caballero', 'Cabbage', 'Calantas', 'Calumpang', 'Camachile', 'Camia', 'Campanilla', 'Carissa', 'Carrot', 'Catmon', 'Cattleya', 'Cauliflower', 'Celery', 'Champaca', 'Chico', 'Coconut', 'Cucumber', 'Cypress', 'Dao', 'Dapdap', 'Dita', 'Duhat', 'Dungon', 'Gladiola', 'Gloriosa', 'Granada', 'Guijo', 'Gumamela', 'Intsia', 'Ipil', 'Jacaranda', 'Jasmine', 'Kaimito', 'Kalachuchi', 'Kalamansi', 'Kamagong', 'Kamias', 'Lanzones', 'Lawaan', 'Lily', 'Lumbayao', 'Mabolo', 'Macapuno', 'Macopa', 'Magnolia', 'Mahogany', 'Malugay', 'Mayapis', 'Melon', 'Milflower', 'Molave', 'Mushroom', 'Mustard', 'Narra', 'Nipa', 'Oleander', 'Oliva', 'Orchid', 'Palm', 'Pandan', 'Pepper', 'Piña', 'Raddish', 'Rosas', 'Sampaguita', 'Sampaloc', 'Santan', 'Santol', 'Sineguelas', 'Squash', 'Supa', 'Talisay', 'Tamarind', 'Tanguile', 'Tindalo', 'Tulip', 'Yakal', 'Zinia'],
  random_object_names: ['Agate', 'Amber', 'Amethyst', 'Aquamarine', 'Citrine', 'Diamond', 'Emerald', 'Garnet', 'Jade', 'Jasper', 'Lapis Lazuli', 'Moonstone', 'Onyx', 'Opal', 'Peridot', 'Ruby', 'Sapphire', 'Sardonyx', 'Sunstone', 'Topaz', 'Turquoise', 'Zircon', 'Apo', 'Arayat', 'Atok', 'Banahaw', 'Bulusan', 'Caraballo', 'Cordillera', 'Cresta', 'Halcon', 'Hibok-Hibok', 'Iriga', 'Kanlaon', 'Makiling', 'Malinao', 'Mariveles', 'Matumtum', 'Mayon', 'Palali', 'Palanan', 'Pao', 'Pinatubo', 'Samat', 'Sicaba', 'Sierra Madre', 'Tabayoc', 'Acacia', 'Agoho', 'Akle', 'Anahaw', 'Anonas', 'Anubing', 'Aranga', 'Asparagus', 'Atis', 'Avocado', 'Azalea', 'Azucena', 'Bagtikan', 'Bakawan', 'Balete', 'Balimbing', 'Banaba', 'Banuyo', 'Banyan', 'Baticulin', 'Batino', 'Bauhinia', 'Bouganvilla', 'Caballero', 'Cabbage', 'Calantas', 'Calumpang', 'Camachile', 'Camia', 'Campanilla', 'Carissa', 'Carrot', 'Catmon', 'Cattleya', 'Cauliflower', 'Celery', 'Champaca', 'Chico', 'Coconut', 'Cucumber', 'Cypress', 'Dao', 'Dapdap', 'Dita', 'Duhat', 'Dungon', 'Gladiola', 'Gloriosa', 'Granada', 'Guijo', 'Gumamela', 'Intsia', 'Ipil', 'Jacaranda', 'Jasmine', 'Kaimito', 'Kalachuchi', 'Kalamansi', 'Kamagong', 'Kamias', 'Lanzones', 'Lawaan', 'Lily', 'Lumbayao', 'Mabolo', 'Macapuno', 'Macopa', 'Magnolia', 'Mahogany', 'Malugay', 'Mayapis', 'Melon', 'Milflower', 'Molave', 'Mushroom', 'Mustard', 'Narra', 'Nipa', 'Oleander', 'Oliva', 'Orchid', 'Palm', 'Pandan', 'Pepper', 'Piña', 'Raddish', 'Rosas', 'Sampaguita', 'Sampaloc', 'Santan', 'Santol', 'Sineguelas', 'Squash', 'Supa', 'Talisay', 'Tamarind', 'Tanguile', 'Tindalo', 'Tulip', 'Yakal', 'Zinia', 'Andromeda', 'Antares', 'Aquarius', 'Aries', 'Asteroid', 'Cancer', 'Canopus', 'Capricorn', 'Comet', 'Constellation', 'Earth', 'Galaxy', 'Gemini', 'Hercules', 'Hydra', 'Juno', 'Jupiter', 'Leo', 'Libra', 'Mars', 'Mercury', 'Milky Way', 'Neptune', 'Orion', 'Pisces', 'Planet', 'Pluto', 'Polaris', 'Sagittarius', 'Saturn', 'Scorpio', 'Taurus', 'Uranus', 'Venus', 'Virgo', 'Zodiac'],
  space_object_names: ['Andromeda', 'Antares', 'Aquarius', 'Aries', 'Asteroid', 'Cancer', 'Canopus', 'Capricorn', 'Comet', 'Constellation', 'Earth', 'Galaxy', 'Gemini', 'Hercules', 'Hydra', 'Juno', 'Jupiter', 'Leo', 'Libra', 'Mars', 'Mercury', 'Milky Way', 'Neptune', 'Orion', 'Pisces', 'Planet', 'Pluto', 'Polaris', 'Sagittarius', 'Saturn', 'Scorpio', 'Taurus', 'Uranus', 'Venus', 'Virgo', 'Zodiac'],
};
