import type { LocaleData } from "../../types";

export const address: Partial<LocaleData> = {
  addressFormats: ['{{street_address}} {{city}}', '{{street_address}} - {{city}}', '{{street_address}} {{city}}, {{administrative_unit}}', '{{street_address}}, {{city}}, {{administrative_unit}}', '{{street_address}} {{city}} - {{administrative_unit}}'],
  buildingNumberFormats: ['%', '%#', '%#', '%##'],
  cities: ['Adrar', 'Reggane', 'Aoulef', 'Timimoun', 'Chlef', 'Ténès', 'Boukadir', 'Laghouat', 'Aflou', 'Aïn Madhi', 'Oum El Bouaghi', 'Aïn Mlila', 'Aïn Beïda', 'Batna', 'Barika', 'Aïn Touta', 'Arris', 'N\'Gaous', 'Béjaïa', 'Akbou', 'Kherrata', 'Taklast', 'Amizour', 'Biskra', 'Tolga', 'Sidi Okba', 'Zéribet El Oued', 'Béchar', 'Taghit', 'Kenadsa', 'Blida', 'Boufarik', 'Larbaa', 'Bouinan', 'Bouira', 'Sour El Ghozlane', 'Aïn Bessem', 'Tamanrasset', 'Ablessa', 'Tébessa', 'Bir El Ater', 'El Aouinet', 'Tlemcen', 'Maghnia', 'Ghazaouet', 'Nedroma', 'Marsa Ben M\'Hidi', 'Tiaret', 'Sougueur', 'Frenda', 'Takhmaret', 'Tizi Ouzou', 'Draa Ben Khedda', 'Azeffoun', 'Boughni', 'Tigzirt', 'Alger Centre', 'Bab El Oued', 'La Casbah', 'Sidi M\'Hamed', 'Hussein Dey', 'El Harrach', 'Rouiba', 'Zéralda', 'Bir Mourad Raïs', 'Bouzaréah', 'Chéraga', 'Draria', 'Bab Ezzouar', 'Bordj El Kiffan', 'Dar El Beïda', 'Aïn Taya', 'Djelfa', 'Messaad', 'Aïn Oussera', 'Hassi Bahbah', 'Jijel', 'El Milia', 'Taher', 'Ziama Mansouriah', 'Sétif', 'El Eulma', 'Djemila', 'Aïn Arnat', 'Bougaa', 'Saïda', 'Aïn El Hadjar', 'Skikda', 'Azzaba', 'El Harrouch', 'Collo', 'Sidi Bel Abbès', 'Aïn El Berd', 'Marhoum', 'Tlemnia', 'Annaba', 'El Bouni', 'Aïn Berda', 'Sidi Amar', 'Guelma', 'Bouchegouf', 'Hammam Debagh', 'Constantine', 'El Khroub', 'Didouche Mourad', 'Zighoud Youcef', 'Aïn Abid', 'Médéa', 'Ksar El Boukhari', 'Berrouaghia', 'Boughzoul', 'Mostaganem', 'Sidi Ali', 'Aïn Tédeles', 'Mazagran', 'M\'Sila', 'Bou Saâda', 'Sidi Aïssa', 'Aïn El Melh', 'Mascara', 'Tighennif', 'Bouhanifia', 'Sig', 'Ouargla', 'Hassi Messaoud', 'Aïn El Beïda', 'Oran', 'Arzew', 'Aïn El Turk', 'Bir El Djir', 'Mers El Hadjadj', 'Es Sénia', 'El Bayadh', 'Brezina', 'Illizi', 'In Amenas', 'Bordj Bou Arreridj', 'Ras El Oued', 'Aïn Taghrout', 'Boumerdès', 'Khemis El Khechna', 'Bordj Menaïel', 'Dellys', 'El Tarf', 'El Kala', 'Ben M\'Hidi', 'Tindouf', 'Tissemsilt', 'Khemisti', 'El Oued', 'Guemar', 'Hassi Khalifa', 'Reguiba', 'Khenchela', 'Babar', 'Souk Ahras', 'Mdaourouch', 'Sedrata', 'Tipaza', 'Cherchell', 'Bou Ismaïl', 'Koléa', 'Mila', 'Ferdjioua', 'Chelghoum Laïd', 'Aïn Defla', 'Khemis Miliana', 'El Attaf', 'Miliana', 'Naâma', 'Mecheria', 'Aïn Sefra', 'Aïn Témouchent', 'Béni Saf', 'Hammam Bou Hadjar', 'Ghardaïa', 'Guerrara', 'Metlili', 'El Atteuf', 'Relizane', 'Mazouna', 'Oued Rhiou', 'Timimoun', 'Bordj Badji Mokhtar', 'Ouled Djellal', 'Béni Abbès', 'In Salah', 'In Guezzam', 'Touggourt', 'Djanet', 'El Meghaier', 'El Menia'],
  postcodeFormats: ['01###', '02###', '03###', '04###', '05###', '06###', '07###', '08###', '09###', '10###', '11###', '12###', '13###', '14###', '15###', '16###', '17###', '18###', '19###', '20###', '21###', '22###', '23###', '24###', '25###', '26###', '27###', '28###', '29###', '30###', '31###', '32###', '33###', '34###', '35###', '36###', '37###', '38###', '39###', '40###', '41###', '42###', '43###', '44###', '45###', '46###', '47###', '48###'],
  streetAddressFormats: ['{{building_number}} {{street_name}}', '{{building_number}}, {{street_name}}'],
  streetNameFormats: ['{{street_prefix}} {{last_name}}', '{{street_prefix}} {{first_name}} {{last_name}}', '{{street_prefix}} de {{last_name}}'],
  streetPrefixes: ['rue', 'avenue', 'boulevard', 'chemin'],
  wilayas: ['Adrar', 'Chlef', 'Laghouat', 'Oum El Bouaghi', 'Batna', 'Béjaïa', 'Biskra', 'Béchar', 'Blida', 'Bouira', 'Tamanrasset', 'Tébessa', 'Tlemcen', 'Tiaret', 'Tizi Ouzou', 'Alger', 'Djelfa', 'Jijel', 'Sétif', 'Saïda', 'Skikda', 'Sidi Bel Abbès', 'Annaba', 'Guelma', 'Constantine', 'Médéa', 'Mostaganem', 'M\'Sila', 'Mascara', 'Ouargla', 'Oran', 'El Bayadh', 'Illizi', 'Bordj Bou Arreridj', 'Boumerdès', 'El Tarf', 'Tindouf', 'Tissemsilt', 'El Oued', 'Khenchela', 'Souk Ahras', 'Tipaza', 'Mila', 'Aïn Defla', 'Naâma', 'Aïn Témouchent', 'Ghardaïa', 'Relizane', 'Timimoun', 'Bordj Badji Mokhtar', 'Ouled Djellal', 'Béni Abbès', 'In Salah', 'In Guezzam', 'Touggourt', 'Djanet', 'El Meghaier', 'El Menia'],
};
